namespaceOverride: k8s-ai

imagePullSecrets: []

backend:
  image:
    repository: docker.io/rahultipledocker/k8s-ai-backend
    tag: 12f5120a7f098daf6eca98e6632dbbf47f096dd4
    pullPolicy: Always
  openai:
    existingSecret: k8s-ai-secret

frontend:
  image:
    repository: docker.io/rahultipledocker/k8s-ai-frontend
    tag: 12f5120a7f098daf6eca98e6632dbbf47f096dd4
    pullPolicy: Always
  service:
    type: NodePort
    nodePort: 30080

postgres:
  persistence:
    enabled: true
    type: hostPath
    hostPath: /var/lib/k8s-ai/postgres
    hostPathType: DirectoryOrCreate
