namespaceOverride: k8s-ai

imagePullSecrets: []

backend:
  image:
    repository: docker.io/rahultipledocker/k8s-ai-backend
    tag: 6871d3bb8dba3e173a128472ed69b407a84b94ac
    pullPolicy: Always
  openai:
    existingSecret: k8s-ai-secret

frontend:
  image:
    repository: docker.io/rahultipledocker/k8s-ai-frontend
    tag: 6871d3bb8dba3e173a128472ed69b407a84b94ac
    pullPolicy: Always
  service:
    type: NodePort
    nodePort: 30080

postgres:
  persistence:
    enabled: true
    type: hostPath
    hostPath: /var/lib/k8s-ai/postgres
    hostPathType: DirectoryOrCreate
