namespaceOverride: k8s-ai

imagePullSecrets: []

backend:
  image:
    repository: docker.io/rahultipledocker/k8s-ai-backend
    tag: 41fcd9ec15a429785bf72637879576e7cbfb0e5c
    pullPolicy: Always
  openai:
    existingSecret: k8s-ai-secret

frontend:
  image:
    repository: docker.io/rahultipledocker/k8s-ai-frontend
    tag: 41fcd9ec15a429785bf72637879576e7cbfb0e5c
    pullPolicy: Always
  service:
    type: NodePort
    nodePort: 30080

postgres:
  persistence:
    enabled: true
    type: hostPath
    hostPath: /var/lib/k8s-ai/postgres
    hostPathType: DirectoryOrCreate
