{{- if .Values.namespaceOverride }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaceOverride }}
  labels:
    {{- include "k8s-ai-troubleshooter.labels" . | nindent 4 }}
{{- end }}
